apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: chatapp
build:
  local:
    push: false
  artifacts:
  - image: atetheone/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
  - image: atetheone/chat-api
    context: chat-api
    docker:
      dockerfile: Dockerfile
    sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
  - image: atetheone/event-broker
    context: event-broker
    docker:
      dockerfile: Dockerfile
    sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
  - infra/k8s/*
